[package]
name = "open-rust"
version = "0.1.0"
authors = ["AbdAllah Aly <aaly90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9"
